{% set name = "pyqg-jax" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1d70f59f9139cb9662be3ae56b345a521fa34d733a5b716d04aef545a7cad37f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - flit-core >=3.9,<4
    - pip
  run:
    - python >=3.9
    - jax >=0.4.6

test:
  imports:
    - pyqg_jax
  commands:
    - pip check
    - JAX_ENABLE_X64=True pytest tests  # [unix]
  source_files:
    - tests
  requires:
    - pip
    - pyqg
    - pytest
    # Spurious dependency from PyQG (affects pip check)
    - cython
    # See issue conda-forge/pyfftw-feedstock#51
    - pyfftw <0.13

about:
  home: https://github.com/karlotness/pyqg-jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    This is a partial port of PyQG to JAX which enables GPU
    acceleration, batching, automatic differentiation, etc.
  summary: Quasigeostrophic model in JAX (port of PyQG)
  doc_url: https://pyqg-jax.readthedocs.io/
  dev_url: https://github.com/karlotness/pyqg-jax

extra:
  recipe-maintainers:
    - karlotness
