{% set name = "pyqg-jax" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cca2ff57429fbcdc259fde400d159c3f64a53569cd27d566f066bb42d1012839

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.9,<4
    - pip
  run:
    - python >={{ python_min }}
    - jax >=0.4.6

test:
  imports:
    - pyqg_jax
  commands:
    - pip check
    - JAX_ENABLE_X64=True pytest tests  # [unix]
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - numpy
    - pyqg
    # Spurious dependency from PyQG (affects pip check)
    - cython
    - python {{ python_min }}

about:
  home: https://github.com/karlotness/pyqg-jax
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: |
    This is a partial port of PyQG to JAX which enables GPU
    acceleration, batching, automatic differentiation, etc.
  summary: Quasigeostrophic model in JAX (port of PyQG)
  doc_url: https://pyqg-jax.readthedocs.io/
  dev_url: https://github.com/karlotness/pyqg-jax

extra:
  recipe-maintainers:
    - karlotness
